### ISSUE TITLE
airtable can not interpret Collections.OrderedDict

### ISSUE THREAD

**Issue by bgriffen** [josephbestjames/airtable.py#16]
If you obtain a record with say attachments which are returned in an ordered dictionary, you have to convert them into a dictionary for them to be updated via at.update() for example. Why not just put the objects in a dictionary in the first place so they are update compatible? When you query airtable for records, there is no ordering mechanism and records are jumbled anyway so I'm not sure for the need of Collections.OrderedDict. It basically just means you have to do some preprocessing as [found here](https://stackoverflow.com/questions/25054003/how-to-convert-a-nested-ordereddict-to-dict) to convert the nested ordered dict to a normal dict. Thanks!

**Comment by vincentwhales** [comment]
I second this. It's a hassle to deal with OrderedDicts.

**Comment by pcorpet** [comment]
The library tries to keep as much info as possible from the API answer, including the order of the fields.

I'll provide an easy way to return dicts (and nested dicts) instead of an OrderedDicts.

**Comment by pcorpet** [comment]
Note that I'm not sure whether the order of the fields in a view are actually returned in their right order in the API but that could be import to be kept.

**Comment by iBobik** [comment]
How about to offer config option to use dictionaries only?

It it really pain to convert nested OrderedDicts.

**Comment by iBobik** [comment]
Aha, that option is there. :-)

Init it like this:
```
airtable.Airtable(
    environ.get("AIRTABLE_BASE"),
    environ.get("AIRTABLE_API_KEY"),
    dict_class=dict
  )
```
