### ISSUE TITLE
Only one field is not supported in get

### ISSUE THREAD

**Issue by iBobik** [josephbestjames/airtable.py#47]
When I try to fetch only one field:
```
airtable().get('People', fields=['Name'])
```
it will not work:
> airtable.airtable.AirtableError: Invalid request: parameter validation failed. Check your request data.

It is because [requests converts one item list to a string](https://github.com/psf/requests/issues/5749#issuecomment-777140208).

Workaround:
```
airtable().get('People', fields=['Name', 'Name'])
```

**Comment by pcorpet** [comment]
Thanks for reporting. I'll use your workaround directly in the code.
