### ISSUE TITLE
Submit to PyPI

### ISSUE THREAD

**Issue by JohnMaguire** [josephbestjames/airtable.py#5]
Hi, I was wondering if you could submit this package to PyPI so that I could add it to my `requirements.txt` with the rest of my dependencies? Thanks for this library!

**Comment by pcorpet** [comment]
FYI, I forked the repo and submitted it to PyPi: https://pypi.python.org/pypi/airtable

**Comment by pcorpet** [comment]
This repo is now the main one used behind https://pypi.python.org/pypi/airtable
